In [5]:
import numpy as np


In [9]:
arr = {0,1,2,3,4,5,6,7,8,9}
arr_ny = np.array(arr)
print(arr_ny)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [6]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr.dtype

dtype('int32')

In [11]:
arr = np.arange(10)
print(arr)

arr_odd = arr[arr%2==1]
arr_even = arr[arr%2==0]
print(arr_odd)
print(arr_even)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0 2 4 6 8]


In [8]:
arr_update_1 = np.where(arr % 2 == 0, arr, 100)
print("result", arr_update_1)

result [  0 100   2 100   4 100   6 100   8 100]


In [12]:
arr = np.arange(10)
print(arr)

arr_odd = arr[1::2]
arr_even = arr[0::2]
print(arr_odd)
print(arr_even)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0 2 4 6 8]
