In [2]:
import numpy as np

# 1. Tạo mảng 3x3 với các giá trị True
arr = np.full((3, 3), True, dtype=bool)
print("1. Mảng 3x3 với giá trị True:")
print(arr)

# 2. Tạo mảng 2 chiều từ arr_1D và thay đổi cột 1 sang cột 3 và ngược lại
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\n2. Mảng sau khi thay đổi cột 1 và cột 3:")
print(arr_2D)

# 3. Đổi dòng 1 sang dòng 2 và ngược lại
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("\n3. Mảng sau khi đổi dòng 1 và dòng 2:")
print(arr_2D)

# 4. Đảo ngược các dòng của arr_2D
arr_2D = arr_2D[::-1, :]
print("\n4. Mảng sau khi đảo ngược các dòng:")
print(arr_2D)

# 5. Đảo ngược các cột của arr_2D
arr_2D = arr_2D[:, ::-1]
print("\n5. Mảng sau khi đảo ngược các cột:")
print(arr_2D)

# 6. Kiểm tra giá trị rỗng trong arr_2D_null
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
contains_nan = np.isnan(arr_2D_null).any()
print("\n6. Kiểm tra giá trị rỗng trong arr_2D_null:")
print(contains_nan)

# 7. Thay thế giá trị null bằng 0 trong arr_2D_null
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\n7. Mảng sau khi thay thế giá trị null bằng 0:")
print(arr_2D_null)


1. Mảng 3x3 với giá trị True:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

2. Mảng sau khi thay đổi cột 1 và cột 3:
[[2 1 0]
 [5 4 3]
 [8 7 6]]

3. Mảng sau khi đổi dòng 1 và dòng 2:
[[5 4 3]
 [2 1 0]
 [8 7 6]]

4. Mảng sau khi đảo ngược các dòng:
[[8 7 6]
 [2 1 0]
 [5 4 3]]

5. Mảng sau khi đảo ngược các cột:
[[6 7 8]
 [0 1 2]
 [3 4 5]]

6. Kiểm tra giá trị rỗng trong arr_2D_null:
True

7. Mảng sau khi thay thế giá trị null bằng 0:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
