In [1]:
import numpy as np
#vd3.3.7.1
#Xóa một phần tử ở vị trí trong mảng
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = 2 #Xóa phần tử 4 ở chỉ mục 2.
new_arr=np.delete(arr,idx_to_delete)

new_arr

array([3, 1, 2, 5])

In [2]:
#Xóa nhiểu phần tử trong mảng
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = [1, 3]
new_arr = np.delete(arr, idx_to_delete)

new_arr

array([3, 4, 5])

In [5]:
#Xóa phần tử trên mảng 2 chiều
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_idx_to_delete = 1
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0)
new_arr_2d

array([1, 3, 4, 5, 6, 7, 8, 9])