In [4]:
import numpy as np
#vd3.3.6.1
#Tìm chỉ mục (vị trí) phần tử trong mảng 1 chiều:
arr = np.array([1, 2, 3, 4, 5])
imdices = np.where(arr==3)
imdices

(array([2], dtype=int64),)

In [6]:
#vd3.3.6.2
arr = np.array([1, 2, 3, 4, 5])
imdices = np.argwhere(arr==3)
imdices

array([[2]], dtype=int64)

In [7]:
#vd3.3.6.3
arr = np.array([1, 5, 2, 3, 4])
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)

print(max_idx)
print(min_idx)

1
0


In [8]:
#vd3.3.6.4
arr = np.array([1, 2, 3, 4, 5])
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3, 4, 5])

In [9]:
arr = np.array([1, 2, 3, 4, 5])
arr.sort()

arr

array([1, 2, 3, 4, 5])

In [10]:
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]

sorted_arr_descending

array([5, 4, 3, 2, 1])

In [11]:
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]

sorted_arr_descending

array([5, 4, 3, 2, 1])