In [1]:
import numpy as np
# Tạo mảng 2 chiều 3x3
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Lấy view mới chỉ chứa 2 dòng và 2 cột của mảng gốc
arr_view = arr_2d[:2, :2].view()
print(arr_view) 

[[1 2]
 [4 5]]


In [2]:
# Thay đổi giá trị trong view
arr_view[0, 0] = 100 #Chỉnh sửa phần tử ở dòng 0, cột 0 thành 10.
print(arr_view) 

[[100   2]
 [  4   5]]


In [3]:
print("Mảng gốc sau khi thay đổi giá trị trong view:")
print(arr_2d) 

Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [4]:
sub_arr=arr[:2,:2] #slicing mảng con lấy 2 dòng, 2 cột của mảng arr
print(sub_arr) 

NameError: name 'arr' is not defined

In [ ]:
sub_arr[0,0]=10 #Chỉnh sửa phần tử ở dòng 0, cột 0 của mảng con thành 10.
print(sub_arr)

In [ ]:
print(arr)

In [ ]:
sub_arr_copy=arr[:2,:2].copy() #Thêm phương thức copy().
print(sub_arr_copy)

In [ ]:
sub_arr_copy[0,0]=10 #sửa phần tử ở dòng 0, cột 0 của mảng
                     # copy thành 10.
print(sub_arr_copy)

In [ ]:
print(arr)

In [5]:
arr=np.arange(1,10) #Tạo mảng một chiều arr có 9 phần tử từ 1-9
grid= arr.reshape((3,3))#chuyển đổi mảng arr thành mảng grid, 3x3
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
x = np.array([1, 2, 3])
x.reshape((1, 3))
x[np.newaxis, :]
print("Số chiều của mảng mới định hình là: \n", x.reshape(1, 3).ndim)
print("Số chiều của mảng x ban đầu là: \n",x.ndim)

Số chiều của mảng mới định hình là: 
 2
Số chiều của mảng x ban đầu là: 
 1


In [8]:
print(x)
print(x.ndim)
y=x[:, np.newaxis]
print(y)
print(y.ndim)

[1 2 3]
1
[[1]
 [2]
 [3]]
2


In [9]:
#vd3.3.4.1
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y]) #Kết hợp ma trận x, y


array([1, 2, 3, 4, 5, 6])

In [13]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng
c = np.concatenate((a, b))
print("result \n", c)

result 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
# Kết hợp theo chiều thứ hai (trục ngang/trục 1) của mảng, trục được đánh chỉ số từ 0.
d = np.concatenate([a, b], axis=1)
print(d)

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
#vd3.3.4.2
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng
c = np.vstack((a, b))
# Kết hợp theo chiều ngang (trục ngang/ trục 1) của mảng
d = np.hstack((a,b))
print(c)
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
#vd3.3.4.3
import numpy as np
arr = np.arange(10) #Tạo mảng arr gồm 10 phần tử từ 0-9
sub_arr1=np.split(arr,[3, 6]) #chia mảng arr theo chỉ mục [3, 6]
#Phần đầu tiên bắt đầu từ chỉ mục 0 và kết thúc trước chỉ mục 3.
#Phần thứ hai bắt đầu từ chỉ mục 3 và kết thúc trước chỉ mục 6.


sub_arr2=np.split(arr,2) #chia mảng arr thành 2 phần bằng nhau
print("Mảng con sub_arr1 là:", sub_arr1, "\n")
print("Mảng con sub_arr2 là:", sub_arr2)

Mảng con sub_arr1 là: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])] 

Mảng con sub_arr2 là: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [16]:
#vd3.3.4.4
import numpy as np
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
upper,lower = np.vsplit(arr,2) #Tách theo trục ngang
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(upper,"\n")
print(lower,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 



In [18]:
left,right=np.hsplit(arr,2) #Tách theo trục dọc
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(left,"\n")
print(right,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 

