In [1]:
import numpy as np
arr1 = np.array([0,1,2])
arr1 + 5

array([5, 6, 7])

In [2]:
arr2 = np.array([5,5,5])
arr1 + arr2

array([5, 6, 7])

In [3]:
arr = np.array([0,1,2])
arr

array([0, 1, 2])

In [5]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [7]:
arr1 = np.arange(3)
arr2 = np.arange(3)[:,np.newaxis]

print(arr1)
print(arr2)

[0 1 2]
[[0]
 [1]
 [2]]


In [8]:
arr1 + arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [9]:
arr1 = np.ones((2,3))
arr2 = np.arange(3)
print(arr1.shape)
print(arr2.shape)

(2, 3)
(3,)


In [10]:
# Tạo mảng dữ liệu với kích thước lớn(1000 phần tử)
data = np.random.randint(100, 200, size=1000)


In [11]:
# Tính toán tỷ lệ phần trăm tăng trưởng của từng phần tử so với giá trị trung bình
mean_value = data.mean()
percentage_growth = (data - mean_value) / mean_value * 100


In [12]:
# In ra 10 phần tử đâu tiên của mảng dữ liệu và tủ lệ phần trăm tăng trưởng
print("Dữ liệu gốc:", data[:10])
print("Tỷ lệ phần trăm tăng trưởng:", percentage_growth[:10])

Dữ liệu gốc: [154 147 179 176 198 169 110 112 179 127]
Tỷ lệ phần trăm tăng trưởng: [  2.86554004  -1.81016632  19.56449135  17.56061719  32.25569434
  12.88491083 -26.52461425 -25.18869815  19.56449135 -15.16932737]
