In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [2]:
# Truy xuất các phần tử bằng một danh sách chỉ mục
indices = [1, 3, 4]
sub_arr_1 = arr[indices]

print(sub_arr_1)

[20 40 50]


In [3]:
# Fancy indexing và boolean
sub_arr_boolean = arr[arr > 50]
print("Orignial Array:\n", arr)

Orignial Array:
 [10 20 30 40 50 60 70 80 90]


In [4]:
# Boolean Indexing
print('After Boolean Condition:', arr[arr>50])

After Boolean Condition: [60 70 80 90]


In [7]:
# Mảng chỉ mục là mảng 2 chiều
idx_arr = np.array([[1,2],
                    [5,6]])
sub_arr_2 = arr[idx_arr]
print(sub_arr_2)

[[20 30]
 [60 70]]
