In [20]:
import pandas as pd
population = pd.Series({'Hà Nội': 8330830,
                        'Quảng Ninh' :1358490, 
                        'Nam Định': 1771000,
                        'Đà Nẵng': 1191381,
                        'TP.Hồ Chí Minh': 9411805})

area=pd.Series({'Hà Nội': 3358.9, 
                'Quảng Ninh': 6177.7,
                'Nam Định': 1668.0,
                'Đà Nẵng': 1284.9,
                'TP.Hồ Chí Minh': 2061.8})

data = pd.DataFrame({'Dân số':population, 'Diện tích' :area})
print(data)

                 Dân số  Diện tích
Hà Nội          8330830     3358.9
Quảng Ninh      1358490     6177.7
Nam Định        1771000     1668.0
Đà Nẵng         1191381     1284.9
TP.Hồ Chí Minh  9411805     2061.8


In [21]:
data['Dân số'] 

Hà Nội            8330830
Quảng Ninh        1358490
Nam Định          1771000
Đà Nẵng           1191381
TP.Hồ Chí Minh    9411805
Name: Dân số, dtype: int64

In [22]:
data['population'] = data['Dân số']
print(data)

                 Dân số  Diện tích  population
Hà Nội          8330830     3358.9     8330830
Quảng Ninh      1358490     6177.7     1358490
Nam Định        1771000     1668.0     1771000
Đà Nẵng         1191381     1284.9     1191381
TP.Hồ Chí Minh  9411805     2061.8     9411805


In [23]:
data.population

Hà Nội            8330830
Quảng Ninh        1358490
Nam Định          1771000
Đà Nẵng           1191381
TP.Hồ Chí Minh    9411805
Name: population, dtype: int64

In [24]:
data['Mật độ'] = data['Dân số']/data['Diện tích']
data

Dân số  Diện tích  population       Mật độ
Hà Nội          8330830     3358.9     8330830  2480.225669
Quảng Ninh      1358490     6177.7     1358490   219.902229
Nam Định        1771000     1668.0     1771000  1061.750600
Đà Nẵng         1191381     1284.9     1191381   927.216904
TP.Hồ Chí Minh  9411805     2061.8     9411805  4564.848676

In [25]:
arr_data = data.values # Lấy mảng dữ liệu gốc từ DataFrameprint(arr_data) 
print(arr_data)
print('Kiểu dữ liệu của arr_data là: ', type(arr_data))

[[8.33083000e+06 3.35890000e+03 8.33083000e+06 2.48022567e+03]
 [1.35849000e+06 6.17770000e+03 1.35849000e+06 2.19902229e+02]
 [1.77100000e+06 1.66800000e+03 1.77100000e+06 1.06175060e+03]
 [1.19138100e+06 1.28490000e+03 1.19138100e+06 9.27216904e+02]
 [9.41180500e+06 2.06180000e+03 9.41180500e+06 4.56484868e+03]]
Kiểu dữ liệu của arr_data là:  <class 'numpy.ndarray'>


In [26]:
data.T

Hà Nội    Quảng Ninh      Nam Định       Đà Nẵng  \
Dân số      8.330830e+06  1.358490e+06  1.771000e+06  1.191381e+06   
Diện tích   3.358900e+03  6.177700e+03  1.668000e+03  1.284900e+03   
population  8.330830e+06  1.358490e+06  1.771000e+06  1.191381e+06   
Mật độ      2.480226e+03  2.199022e+02  1.061751e+03  9.272169e+02   

            TP.Hồ Chí Minh  
Dân số        9.411805e+06  
Diện tích     2.061800e+03  
population    9.411805e+06  
Mật độ        4.564849e+03

In [27]:
print("Cách 1, sử dụng chuyển vị:", data.T.values[1]) 
print("Cách 2, sử dụng chỉ mục(index): ", data['Diện tích'].values) 

Cách 1, sử dụng chuyển vị: [3358.9 6177.7 1668.  1284.9 2061.8]
Cách 2, sử dụng chỉ mục(index):  [3358.9 6177.7 1668.  1284.9 2061.8]


In [28]:
#Sử dụng loc
print('$1', data)
#Lấy hàng đầu tiên
print('\n$2 Dữ liệu của Hà Nội:\n',data.loc['Hà Nội'])
#Lấy dữ liệu 3 hàng đầu tiên
print("\n$3 Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:\n",data.loc[:'Nam Định']) 
#Dữ liệu của 2 hàng và 2 cột đầu tiên
print("\n$4 Dữ liệu dân số, diện tích của Hà Nội, Quảng Ninh:\n",data.loc[:'Quảng Ninh',:'Diện tích'])
#Lấy dữ liệu của tất cả các hàng và các cột cuối cùng 
print("\n$5 Mật độ dân số các Tỉnh/Thành phố:\n",data.loc[:,'Mật độ'])

$1                  Dân số  Diện tích  population       Mật độ
Hà Nội          8330830     3358.9     8330830  2480.225669
Quảng Ninh      1358490     6177.7     1358490   219.902229
Nam Định        1771000     1668.0     1771000  1061.750600
Đà Nẵng         1191381     1284.9     1191381   927.216904
TP.Hồ Chí Minh  9411805     2061.8     9411805  4564.848676

$2 Dữ liệu của Hà Nội:
 Dân số        8.330830e+06
Diện tích     3.358900e+03
population    8.330830e+06
Mật độ        2.480226e+03
Name: Hà Nội, dtype: float64

$3 Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:
              Dân số  Diện tích  population       Mật độ
Hà Nội      8330830     3358.9     8330830  2480.225669
Quảng Ninh  1358490     6177.7     1358490   219.902229
Nam Định    1771000     1668.0     1771000  1061.750600

$4 Dữ liệu dân số, diện tích của Hà Nội, Quảng Ninh:
              Dân số  Diện tích
Hà Nội      8330830     3358.9
Quảng Ninh  1358490     6177.7

$5 Mật độ dân số các Tỉnh/Thành phố:
 Hà Nội         

In [29]:
print(data)
#Lấy hàng đầu tiên
print("\n!1 Dữ liệu của thủ đô Hà Nội:\n",data.iloc[0])
#Lấy dữ liệu 3 hàng đầu tiên
print("\n!2 Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:\n",data.iloc[0:3]) 
#Lấy dữ liệu 2 hàng, 2 cột đầu tiên
print("\n!3 Dữ liệu dân số và diện tích của Hà Nội và Quảng Ninh:\n",data.iloc[:2,:2])
#Lấy dữ liệu về mật độ dân số của các tỉnh còn lại 
print("\n!4 Mật độ dân số của các tỉnh/thành phố:\n",data.iloc[:,-1])

                 Dân số  Diện tích  population       Mật độ
Hà Nội          8330830     3358.9     8330830  2480.225669
Quảng Ninh      1358490     6177.7     1358490   219.902229
Nam Định        1771000     1668.0     1771000  1061.750600
Đà Nẵng         1191381     1284.9     1191381   927.216904
TP.Hồ Chí Minh  9411805     2061.8     9411805  4564.848676

!1 Dữ liệu của thủ đô Hà Nội:
 Dân số        8.330830e+06
Diện tích     3.358900e+03
population    8.330830e+06
Mật độ        2.480226e+03
Name: Hà Nội, dtype: float64

!2 Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:
              Dân số  Diện tích  population       Mật độ
Hà Nội      8330830     3358.9     8330830  2480.225669
Quảng Ninh  1358490     6177.7     1358490   219.902229
Nam Định    1771000     1668.0     1771000  1061.750600

!3 Dữ liệu dân số và diện tích của Hà Nội và Quảng Ninh:
              Dân số  Diện tích
Hà Nội      8330830     3358.9
Quảng Ninh  1358490     6177.7

!4 Mật độ dân số của các tỉnh/thành phố:
 Hà 

In [30]:
print('\n Lấy dữ liệu dân số và mật độ của Tỉnh/TP mà diện tích > 2000km2:\n')
print(data.loc[data['Diện tích']>2000, ['Dân số', 'Mật độ', 'Diện tích']])


 Lấy dữ liệu dân số và mật độ của Tỉnh/TP mà diện tích > 2000km2:

                 Dân số       Mật độ  Diện tích
Hà Nội          8330830  2480.225669     3358.9
Quảng Ninh      1358490   219.902229     6177.7
TP.Hồ Chí Minh  9411805  4564.848676     2061.8


In [31]:
# Lấy dữ liệu của Tỉnh/TP có mật độ < 1000 và dân số > 1 triệu
print(data.loc[(data['Mật độ'] < 1000) & (data['Dân số'] > 1000000)])

             Dân số  Diện tích  population      Mật độ
Quảng Ninh  1358490     6177.7     1358490  219.902229
Đà Nẵng     1191381     1284.9     1191381  927.216904


In [32]:
#Sử dụng slicing
print(data[0:2])

             Dân số  Diện tích  population       Mật độ
Hà Nội      8330830     3358.9     8330830  2480.225669
Quảng Ninh  1358490     6177.7     1358490   219.902229


In [33]:
#masking
print(data[data['Dân số']>1000])

                 Dân số  Diện tích  population       Mật độ
Hà Nội          8330830     3358.9     8330830  2480.225669
Quảng Ninh      1358490     6177.7     1358490   219.902229
Nam Định        1771000     1668.0     1771000  1061.750600
Đà Nẵng         1191381     1284.9     1191381   927.216904
TP.Hồ Chí Minh  9411805     2061.8     9411805  4564.848676
