In [2]:
import pandas as pd
import numpy as np

In [4]:
#Tạo một mảng NumPy 2 chiều (3,4) từ 10 phân tử ngẫu nhiên 0-->9
arr = np.random.randint(10,size=(3,4))
arr

array([[7, 5, 7, 9],
       [6, 6, 9, 8],
       [6, 3, 2, 1]])

In [5]:
arr-arr[0]

array([[ 0,  0,  0,  0],
       [-1,  1,  2, -1],
       [-1, -2, -5, -8]])

In [7]:
#Tạo DataFrame df từ mảng NumPy arr, với các cột là P, Q, M, N
df = pd.DataFrame(arr,columns=['P','Q','M','N'])
print("df:\n",df)
#Tính toán hiệu của df với phần tử tương ứng trong hàng đầu của nó
df-df.iloc[0] 

df:
    P  Q  M  N
0  7  5  7  9
1  6  6  9  8
2  6  3  2  1


P  Q  M  N
0  0  0  0  0
1 -1  1  2 -1
2 -1 -2 -5 -8

In [8]:
# Trừ các phần tử trong DataFrame với cột 'Q'.
print("df1:\n", df.subtract(df['Q'], axis=0))
# Nhân các phần tử của df với cột 'N'.
print("df2:\n", df.multiply(df['N'], axis=0))

df1:
    P  Q  M  N
0  2  0  2  4
1  0  0  3  2
2  3  0 -1 -2
df2:
     P   Q   M   N
0  63  45  63  81
1  48  48  72  64
2   6   3   2   1


In [9]:
even = df[df %2 ==0].iloc[:,::2]
print("even \n", even)
print("Các phần tử chẵn ở cột 'P'và 'M' là :\n", even)

even 
      P    M
0  NaN  NaN
1  6.0  NaN
2  6.0  2.0
Các phần tử chẵn ở cột 'P'và 'M' là :
      P    M
0  NaN  NaN
1  6.0  NaN
2  6.0  2.0


In [10]:
arr=np.array([1,2,None, 3])
arr

array([1, 2, None, 3], dtype=object)

In [14]:
for dtype in ['object','int']:
  print("dtype=",dtype)
  %timeit np.arange(1E6,dtype=dtype).sum()  
  print()

dtype= object
154 ms ± 26.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

dtype= int
3.91 ms ± 468 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [12]:
import numpy as np
arr=np.array([1,np.nan, 3,4])
print(arr.dtype) #in ra kiểu dữ liệu của arr
arr 

float64


array([ 1., nan,  3.,  4.])

In [13]:
#Tính các giá trị trong mảng arr như: tổng các phần tử, min, max
arr.sum(), arr.min(), arr.max()

(nan, nan, nan)

In [3]:
sr = pd.Series([1,2, np.nan, 4, None])
sr

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [4]:
int_sr1 = pd.Series([1,2,3])
int_sr1

0    1
1    2
2    3
dtype: int64

In [7]:
nan_sr = pd.Series([1,2,np.nan],dtype=pd.Int64Dtype())
nan_sr

0       1
1       2
2    <NA>
dtype: Int64

In [8]:
st_sr = pd.Series(['Uneti', 'Khưd', None, np.nan])
st_sr

0    Uneti
1     Khưd
2     None
3      NaN
dtype: object

In [9]:
st_sr.isnull()

0    False
1    False
2     True
3     True
dtype: bool

In [10]:
st_sr[st_sr.notnull()]

0    Uneti
1     Khưd
dtype: object

In [11]:
print(type(st_sr.notnull()))

<class 'pandas.core.series.Series'>


In [16]:
# Tạo DataFrame có chứa giá trị null
data = {'A': [1, 2, np.nan, 4],
        'B': [np.nan, 6, 7, 8],
        'C': [9, 10, 11, 12]}
df = pd.DataFrame(data)
print("DataFrame ban đầu: \n",df)

#Kiểm tra giá trị null trong DataFrame
print(df.isnull())
print(df.notnull)

DataFrame ban đầu: 
      A    B   C
0  1.0  NaN   9
1  2.0  6.0  10
2  NaN  7.0  11
3  4.0  8.0  12
       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False  False
<bound method DataFrame.notnull of      A    B   C
0  1.0  NaN   9
1  2.0  6.0  10
2  NaN  7.0  11
3  4.0  8.0  12>


In [18]:
drop_st = st_sr.dropna()
print('Series mới: \n', drop_st)
print('Series ban đầu: \n', st_sr)

Series mới: 
 0    Uneti
1     Khưd
dtype: object
Series ban đầu: 
 0    Uneti
1     Khưd
2     None
3      NaN
dtype: object


In [19]:
print(df,"\n")
df['A'] = np.nan
print(df,"\n")

df.dropna(how = 'all', axis=1)

     A    B   C
0  1.0  NaN   9
1  2.0  6.0  10
2  NaN  7.0  11
3  4.0  8.0  12 

    A    B   C
0 NaN  NaN   9
1 NaN  6.0  10
2 NaN  7.0  11
3 NaN  8.0  12 



B   C
0  NaN   9
1  6.0  10
2  7.0  11
3  8.0  12

In [20]:
data = pd.Series([1, np.nan, 2, None, 3], index = list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [21]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64